dist: bionic

language: java

jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/*/*.lock
  - rm -f  $HOME/.gradle/caches/*/*/*.lock
  - rm -fr $HOME/.gradle/caches/journal-1/
  - rm -fr $HOME/.gradle/caches/*/gradle-kotlin-dsl*
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
