
// Generated by Akka gRPC. DO NOT EDIT.
package com.example.shoppingcart;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;


public interface ShoppingCart {
  
  
  java.util.concurrent.CompletionStage<com.google.protobuf.Empty> addItem(ShoppingCartProto.AddLineItem in);


  java.util.concurrent.CompletionStage<com.google.protobuf.Empty> removeItem(ShoppingCartProto.RemoveLineItem in);


  java.util.concurrent.CompletionStage<ShoppingCartProto.Cart> getCart(ShoppingCartProto.GetShoppingCart in);


  static String name = "com.example.shoppingcart.ShoppingCart";

  public static class Serializers {

      public static ProtobufSerializer<ShoppingCartProto.GetShoppingCart> GetShoppingCartSerializer = new GoogleProtobufSerializer<>(ShoppingCartProto.GetShoppingCart.class);

      public static ProtobufSerializer<ShoppingCartProto.Cart> CartSerializer = new GoogleProtobufSerializer<>(ShoppingCartProto.Cart.class);

      public static ProtobufSerializer<com.google.protobuf.Empty> EmptySerializer = new GoogleProtobufSerializer<>(com.google.protobuf.Empty.class);

      public static ProtobufSerializer<ShoppingCartProto.AddLineItem> AddLineItemSerializer = new GoogleProtobufSerializer<>(ShoppingCartProto.AddLineItem.class);

      public static ProtobufSerializer<ShoppingCartProto.RemoveLineItem> RemoveLineItemSerializer = new GoogleProtobufSerializer<>(ShoppingCartProto.RemoveLineItem.class);
    
  }
}
