
// Generated by Akka gRPC. DO NOT EDIT.
package com.example.shoppingcart;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class ShoppingCartClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer addItem(com.example.shoppingcart.ShoppingCartProto.AddLineItem) if possible.
     */
    
      public SingleResponseRequestBuilder<ShoppingCartProto.AddLineItem, com.google.protobuf.Empty> addItem()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer removeItem(com.example.shoppingcart.ShoppingCartProto.RemoveLineItem) if possible.
     */

      public SingleResponseRequestBuilder<ShoppingCartProto.RemoveLineItem, com.google.protobuf.Empty> removeItem()

    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getCart(com.example.shoppingcart.ShoppingCartProto.GetShoppingCart) if possible.
     */

      public SingleResponseRequestBuilder<ShoppingCartProto.GetShoppingCart, ShoppingCartProto.Cart> getCart()

    {
        throw new UnsupportedOperationException();
    }
  
}
