
// Generated by Akka gRPC. DO NOT EDIT.
package io.cloudstate.protocol;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;
import akka.grpc.javadsl.Metadata;
import akka.grpc.GrpcServiceException;
import io.cloudstate.protocol.Crdt;
import io.grpc.Status;

public interface CrdtPowerApi extends Crdt {
  
  akka.stream.javadsl.Source<io.cloudstate.protocol.CrdtProto.CrdtStreamOut, akka.NotUsed> handle(akka.stream.javadsl.Source<io.cloudstate.protocol.CrdtProto.CrdtStreamIn, akka.NotUsed> in, Metadata metadata);
  

  
  default akka.stream.javadsl.Source<io.cloudstate.protocol.CrdtProto.CrdtStreamOut, akka.NotUsed> handle(akka.stream.javadsl.Source<io.cloudstate.protocol.CrdtProto.CrdtStreamIn, akka.NotUsed> in) {
    throw new GrpcServiceException(Status.UNIMPLEMENTED);
  }
  

  static String name = "cloudstate.crdt.Crdt";

  public static class Serializers {
    
      public static ProtobufSerializer<io.cloudstate.protocol.CrdtProto.CrdtStreamIn> CrdtStreamInSerializer = new GoogleProtobufSerializer<>(io.cloudstate.protocol.CrdtProto.CrdtStreamIn.class);
    
      public static ProtobufSerializer<io.cloudstate.protocol.CrdtProto.CrdtStreamOut> CrdtStreamOutSerializer = new GoogleProtobufSerializer<>(io.cloudstate.protocol.CrdtProto.CrdtStreamOut.class);
    
  }
}
