
// Generated by Akka gRPC. DO NOT EDIT.
package io.cloudstate.protocol;


import akka.grpc.javadsl.StreamResponseRequestBuilder;


public abstract class CrdtClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer handle(io.cloudstate.protocol.CrdtProto.CrdtStreamIn) if possible.
     */
    
      public StreamResponseRequestBuilder<akka.stream.javadsl.Source<io.cloudstate.protocol.CrdtProto.CrdtStreamIn, akka.NotUsed>, io.cloudstate.protocol.CrdtProto.CrdtStreamOut> handle()
    
    {
        throw new UnsupportedOperationException();
    }
  
}
