
// Generated by Akka gRPC. DO NOT EDIT.
package io.cloudstate.protocol;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class EntityDiscoveryClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer discover(io.cloudstate.protocol.EntityProto.ProxyInfo) if possible.
     */
    
      public SingleResponseRequestBuilder<io.cloudstate.protocol.EntityProto.ProxyInfo, io.cloudstate.protocol.EntityProto.EntitySpec> discover()
    
    {
        throw new UnsupportedOperationException();
    }

    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer reportError(io.cloudstate.protocol.EntityProto.UserFunctionError) if possible.
     */

      public SingleResponseRequestBuilder<io.cloudstate.protocol.EntityProto.UserFunctionError, com.google.protobuf.Empty> reportError()

    {
        throw new UnsupportedOperationException();
    }
  
}
