
// Generated by Akka gRPC. DO NOT EDIT.
package io.cloudstate.protocol;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;
import akka.grpc.javadsl.Metadata;
import akka.grpc.GrpcServiceException;
import io.cloudstate.protocol.EventSourced;
import io.grpc.Status;

public interface EventSourcedPowerApi extends EventSourced {
  
  akka.stream.javadsl.Source<io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamOut, akka.NotUsed> handle(akka.stream.javadsl.Source<io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamIn, akka.NotUsed> in, Metadata metadata);
  

  
  default akka.stream.javadsl.Source<io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamOut, akka.NotUsed> handle(akka.stream.javadsl.Source<io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamIn, akka.NotUsed> in) {
    throw new GrpcServiceException(Status.UNIMPLEMENTED);
  }
  

  static String name = "cloudstate.eventsourced.EventSourced";

  public static class Serializers {
    
      public static ProtobufSerializer<io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamIn> EventSourcedStreamInSerializer = new GoogleProtobufSerializer<>(io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamIn.class);
    
      public static ProtobufSerializer<io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamOut> EventSourcedStreamOutSerializer = new GoogleProtobufSerializer<>(io.cloudstate.protocol.EventSourcedProto.EventSourcedStreamOut.class);
    
  }
}
