
// Generated by Akka gRPC. DO NOT EDIT.
package io.cloudstate.protocol;

import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;


public interface StatelessFunction {
  
  
  java.util.concurrent.CompletionStage<io.cloudstate.protocol.FunctionProto.FunctionReply> handleUnary(io.cloudstate.protocol.FunctionProto.FunctionCommand in);
  
  
  java.util.concurrent.CompletionStage<io.cloudstate.protocol.FunctionProto.FunctionReply> handleStreamedIn(akka.stream.javadsl.Source<io.cloudstate.protocol.FunctionProto.FunctionCommand, akka.NotUsed> in);
  
  
  akka.stream.javadsl.Source<io.cloudstate.protocol.FunctionProto.FunctionReply, akka.NotUsed> handleStreamedOut(io.cloudstate.protocol.FunctionProto.FunctionCommand in);
  
  
  akka.stream.javadsl.Source<io.cloudstate.protocol.FunctionProto.FunctionReply, akka.NotUsed> handleStreamed(akka.stream.javadsl.Source<io.cloudstate.protocol.FunctionProto.FunctionCommand, akka.NotUsed> in);
  

  static String name = "cloudstate.function.StatelessFunction";

  public static class Serializers {
    
      public static ProtobufSerializer<io.cloudstate.protocol.FunctionProto.FunctionCommand> FunctionCommandSerializer = new GoogleProtobufSerializer<>(io.cloudstate.protocol.FunctionProto.FunctionCommand.class);
    
      public static ProtobufSerializer<io.cloudstate.protocol.FunctionProto.FunctionReply> FunctionReplySerializer = new GoogleProtobufSerializer<>(io.cloudstate.protocol.FunctionProto.FunctionReply.class);
    
  }
}
